package org.example.solution;

public class TestVectors {

  public static final String TEST_CASE_SENTENCE = "This is a very long sentence and I want to educate everyone in this whole crazy world….";

  public static final String TEST_SENTENCE_WITH_SPECIAL_CHARS = "hello, this's <a> Aung& !and #say $world %^hello";
  // TEST_SENTENCE with 1079 words
  public static final String TEST_SENTENCE =
      "The responsibility of the media to act as an avenue for social change has been ignored for several years when various TV shows have presented various programs to serve capitalism. In this way, information is conveyed to the audience without engaging the audience in the production of those shows and hence these shows normally serve the purpose of entertainment but ignore the important part of transforming the society. When the audiences are involved in the production of these programs, the content of these programs will affect the audience directly or indirectly and hence capable of changing their way of thinking or attitudes on certain issues that affect our society such as challenging racism (Alia, 2004).\n"
          + "The responsibility to transform the society socially therefore lies on the producers and the users of these shows and not the owners or the investors of these media avenues. The role of the users will be to influence the producers while the producers’ role is to produce and direct these shows for the society. The producer therefore should use his or her professional skills to produce for the society. However, he or she cannot make a great impact alone and therefore has to involve everyone in the society.\n"
          + "As stated by Bartkowiak (2009), the possibility of changing our society through TV shows depends on the involvement of the society just like in other media like the newspapers and magazines. One of the ways of ensuring that every one in the society is involved is to focus on documentary shows. Unlike other programs that mainly follow the commercial pattern, documentary shows are capable of transforming our society as well as achieving success in media entertainment business (Yadav, 2004).\n"
          + "A television show that promotes a better understanding of each other in the society is the one that is capable of transforming that society. Better understanding is vital for resolving social conflicts among different groups in the society. ‘’Konkonkon is a documentary of life of ‘’no body’’. This show presents different individuals in depth and reflects the conflicts in the society.\n"
          + "No body here means people who are homeless, disabled persons, prostitutes, and other disadvantaged people in the society who are often forgotten in the society and that’s the reason the show named them nobody. Most of the public media have no room for this people as they assume that they do not exist since there is no show that focuses mainly on them to show that they exist. This show involves presentation of someone’s everyday life and how the person goes on expressing personality, individual traits and character rather than suppressing them to adopt a role (Nichols, 2010).\n"
          + "The name of the show itself is very important as it tells from the first insight what the show entails and therefore one is able to reflect what probably is in the show. This show is important for the society since it gives these challenged people an opportunity to present their case over the media that has often ignored them. This takes place through their participation as guests in these shows. They have an opportunity to share their story in the society and to let others know that they are ‘’human’’ a value as a part of this society.\n"
          + "The search for these guests are very important since the guest that will appear in this kind of show has a greater impact on the audience. The guest should therefore be a role model to nobody person. They should also be people who are able to testify their stories freely without any condition or favoritism of any manner. This person has to be one who had transformed from nobody to somebody for him to be qualified as a guest and as a role model. In this way these people are able to use the media as a propaganda tool to represent themselves and from their stories they are able to inspire and transform the society.\n"
          + "Once a theme has been developed, the searches for the guests begin. This can be done through moving within the society informing people about the topic and the people come and that’s when the qualified person is chosen. The qualified people are also got from the audiences of this particular show through their comments about the show. The activities of these people are therefore watched and the project may take even a whole year. This is very important to ensure the content of that particular show is as accurate as possible. In this way the show presents a real life story telling by the guest without directing.\n"
          + "This kind of show has the effects of transforming the way of thinking of several audiences as most of them will be asking themselves questions that they answer themselves while others will be sympathizing with the quests hence they get inspired. It also highlights the notion of the public and how popular genres are connected in the society (Hill, 2007). This is very important for the social change.\n"
          + "It is also true that when the audiences are frequently subjected to questioning their lives, they learn and quickly fix the knowledge into their minds and therefore helps them change their mind after watching the show. This may be racism or even segregation that is affecting the society. Documentary TV shows has therefore moved from those days that they reflected the uncertainties and tensions of the modern world (Chapman, 2009).\n"
          + "This shows that the participation of the audiences, the guests and the quality of the quests are very important for the producer of this show and hence the participation of everyone in the process is the key to success of the show in transforming the society. What is important here for the producer is therefore to enable the society develop new thought, sediment new knowledge and put this particular knowledge into action. This then results to the change in the society thinking and attitudes concerning certain issues in the society.\n"
          + "The focus in the media therefore should be to transform the society and not mainly commercialize the shows just for self gaining. We should think about the society that we live in and ask ourselves who will clean our house for us or do we leave our own house dirty and proceed to clean others. It is important to note that even though we may be making a lot of profit the society may not be at peace and we should always do what we think is the best.\n";
}
